### ISSUE TITLE
Conversation

### ISSUE THREAD

**Issue by lsproule** [jherr/astro-2-video-code#4]
Hey,

I would really love to talk to you more about this.

https://calendly.com/lucas-sproule-42/30min?month=2023-01

I have an idea for how we could use this as a really good way for content creators to be able to manage their content. Like for example if we were to add functionality instead of just using iframes to embed the content. We could actually upload the content to say s3 or really any blob storage/ Potentially allowing the website to have access to a specific folder on say a nas, so that content creators can do 2 things.

1. they can catalog all of their video content
2. allow them to upload to all social medias at the same time

so Imagine if for a video you could put your shorts and full length videos in the same slug, and then, you could use it to publish your videos to all attached social media accounts.

Why would this be useful? Uploading content to all social media platforms can be daunting, so if there were a way to be able to do all of this at once. We could probably capitalize on this.

Not to mention because this is a collection of works that may not all be uploaded. It could have potentially down the road almost patreon support levels, so that people can see creators unreleased content.

I have a lot more ideas, and I hope you are interested as well.

**Comment by jherr** [comment]
These are interesting ideas. For the moment though I just need a catalog for my YouTube videos.
