### ISSUE TITLE
Just a heads up to everyone, you must use pnpm to install this

### ISSUE THREAD

**Issue by DelphiCoder** [jherr/astro-2-video-code#5]
# 📌 Just a heads up to everyone, you must use pnpm to install this.

## 😮 This will not work [Edit: unless you also have pnpm already installed]:

`$ npm i`

## 🌟 You need to install pnpm by following instructions from here: 

https://pnpm.io/installation

## 😃 Then you can do:

`pnpm i`

## 💀 Going `npm i` will give you errors like:

`npm ERR! code ERESOLVE`

and

`npm ERR! ERESOLVE unable to resolve dependency tree`

## ✨ Now you can enjoy Jack's contribution! 

Have fun and code responsibly....

**Comment by youssef-devx** [comment]
I am afraid to tell you that using ```npm i``` worked for me

**Comment by DelphiCoder** [comment]
It installs for me too using `npm i` AFTER I installed pnpm but not before.
